# Site settings
title: Partially Applied
description: Ross Gardiner's blog.
baseurl: ""
url: "http://rossng.github.io" # the base hostname & protocol for your site
github_username:  rossng

# Build settings
markdown: kramdown

collections:
  - cv_entries

paginate: 5